//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace StratML.Core.Two {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class PerformancePlanOrReport {
        
        private string nameField;
        
        private string descriptionField;
        
        private string otherInformationField;
        
        private StrategicPlanCore strategicPlanCoreField;
        
        private AdministrativeInformationType administrativeInformationField;
        
        private ContactInformationType submitterField;
        
        private PerformancePlanOrReportType typeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        public StrategicPlanCore StrategicPlanCore {
            get {
                return this.strategicPlanCoreField;
            }
            set {
                this.strategicPlanCoreField = value;
            }
        }
        
        /// <remarks/>
        public AdministrativeInformationType AdministrativeInformation {
            get {
                return this.administrativeInformationField;
            }
            set {
                this.administrativeInformationField = value;
            }
        }
        
        /// <remarks/>
        public ContactInformationType Submitter {
            get {
                return this.submitterField;
            }
            set {
                this.submitterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PerformancePlanOrReportType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        [XmlIgnore]
        public string id { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class StrategicPlanCore {
        
        private Organization[] organizationField;
        
        private Vision visionField;
        
        private Mission missionField;
        
        private Value[] valueField;
        
        private Goal[] goalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization")]
        public Organization[] Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public Vision Vision {
            get {
                return this.visionField;
            }
            set {
                this.visionField = value;
            }
        }
        
        /// <remarks/>
        public Mission Mission {
            get {
                return this.missionField;
            }
            set {
                this.missionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public Value[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Goal")]
        public Goal[] Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Organization {
        
        private string nameField;
        
        private string acronymField;
        
        private string identifierField;
        
        private string descriptionField;
        
        private Stakeholder[] stakeholderField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Acronym {
            get {
                return this.acronymField;
            }
            set {
                this.acronymField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Stakeholder {
        
        private string nameField;
        
        private string descriptionField;
        
        private Role[] roleField;
        
        private StakeholderStakeholderTypeType stakeholderTypeTypeField;
        
        private bool stakeholderTypeTypeFieldSpecified;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Role")]
        public Role[] Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StakeholderStakeholderTypeType StakeholderTypeType {
            get {
                return this.stakeholderTypeTypeField;
            }
            set {
                this.stakeholderTypeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StakeholderTypeTypeSpecified {
            get {
                return this.stakeholderTypeTypeFieldSpecified;
            }
            set {
                this.stakeholderTypeTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Role {
        
        private string nameField;
        
        private string descriptionField;
        
        private RoleType[] roleTypeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleType")]
        public RoleType[] RoleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public enum RoleType {
        
        /// <remarks/>
        Performer,
        
        /// <remarks/>
        Beneficiary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public partial class GoalType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string identifierField;
        
        private string sequenceIndicatorField;
        
        private Stakeholder[] stakeholderField;
        
        private string otherInformationField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum StakeholderStakeholderTypeType {
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        Organization,
        
        /// <remarks/>
        Generic_Group,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Vision {
        
        private string descriptionField;
        
        private string identifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Mission {
        
        private string descriptionField;
        
        private string identifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Value {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Goal : GoalType {
        
        private ObjectiveType[] objectiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Objective")]
        public ObjectiveType[] Objective {
            get {
                return this.objectiveField;
            }
            set {
                this.objectiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Objective", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class ObjectiveType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string identifierField;
        
        private string sequenceIndicatorField;
        
        private Stakeholder[] stakeholderField;
        
        private string otherInformationField;
        
        private PerformanceIndicator[] performanceIndicatorField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PerformanceIndicator")]
        public PerformanceIndicator[] PerformanceIndicator {
            get {
                return this.performanceIndicatorField;
            }
            set {
                this.performanceIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class PerformanceIndicator {
        
        private string sequenceIndicatorField;
        
        private string measurementDimensionField;
        
        private string unitOfMeasurementField;
        
        private string identifierField;
        
        private Relationship[] relationshipField;
        
        private MeasurementInstance[] measurementInstanceField;
        
        private string otherInformationField;
        
        private ValueChainStageType valueChainStageField;
        
        private bool valueChainStageFieldSpecified;
        
        private PerformanceIndicatorTypeType performanceIndicatorTypeField;
        
        private bool performanceIndicatorTypeFieldSpecified;
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string MeasurementDimension {
            get {
                return this.measurementDimensionField;
            }
            set {
                this.measurementDimensionField = value;
            }
        }
        
        /// <remarks/>
        public string UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MeasurementInstance")]
        public MeasurementInstance[] MeasurementInstance {
            get {
                return this.measurementInstanceField;
            }
            set {
                this.measurementInstanceField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueChainStageType ValueChainStage {
            get {
                return this.valueChainStageField;
            }
            set {
                this.valueChainStageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueChainStageSpecified {
            get {
                return this.valueChainStageFieldSpecified;
            }
            set {
                this.valueChainStageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PerformanceIndicatorTypeType PerformanceIndicatorType {
            get {
                return this.performanceIndicatorTypeField;
            }
            set {
                this.performanceIndicatorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerformanceIndicatorTypeSpecified {
            get {
                return this.performanceIndicatorTypeFieldSpecified;
            }
            set {
                this.performanceIndicatorTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Relationship {
        
        private string identifierField;
        
        private string[] referentIdentifierField;
        
        private string nameField;
        
        private string descriptionField;
        
        private RelationshipTypeType relationshipTypeField;
        
        private bool relationshipTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferentIdentifier")]
        public string[] ReferentIdentifier {
            get {
                return this.referentIdentifierField;
            }
            set {
                this.referentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RelationshipTypeType RelationshipType {
            get {
                return this.relationshipTypeField;
            }
            set {
                this.relationshipTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelationshipTypeSpecified {
            get {
                return this.relationshipTypeFieldSpecified;
            }
            set {
                this.relationshipTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum RelationshipTypeType {
        
        /// <remarks/>
        Broader_Than,
        
        /// <remarks/>
        Peer_To,
        
        /// <remarks/>
        Narrower_Than,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class MeasurementInstance {
        
        private TargetResult[] targetResultField;
        
        private ActualResult[] actualResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetResult")]
        public TargetResult[] TargetResult {
            get {
                return this.targetResultField;
            }
            set {
                this.targetResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActualResult")]
        public ActualResult[] ActualResult {
            get {
                return this.actualResultField;
            }
            set {
                this.actualResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class TargetResult {
        
        private string startDateField;
        
        private string endDateField;
        
        private string numberOfUnitsField;
        
        private Descriptor descriptorField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string NumberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
            }
        }
        
        /// <remarks/>
        public Descriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Descriptor {
        
        private string descriptorNameField;
        
        private string descriptorValueField;
        
        /// <remarks/>
        public string DescriptorName {
            get {
                return this.descriptorNameField;
            }
            set {
                this.descriptorNameField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptorValue {
            get {
                return this.descriptorValueField;
            }
            set {
                this.descriptorValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class ActualResult {
        
        private string startDateField;
        
        private string endDateField;
        
        private string numberOfUnitsField;
        
        private Descriptor descriptorField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string NumberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
            }
        }
        
        /// <remarks/>
        public Descriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum ValueChainStageType {
        
        /// <remarks/>
        Outcome,
        
        /// <remarks/>
        Output_Processing,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        Input_Processing,
        
        /// <remarks/>
        Input,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum PerformanceIndicatorTypeType {
        
        /// <remarks/>
        Quantitative,
        
        /// <remarks/>
        Qualitative,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("AdministrativeInformation", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class AdministrativeInformationType {
        
        private string identifierField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string publicationDateField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Submitter", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class ContactInformationType {
        
        private string identifierField;
        
        private string givenNameField;
        
        private string surnameField;
        
        private string phoneNumberField;
        
        private string emailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum PerformancePlanOrReportType {
        
        /// <remarks/>
        Strategic_Plan,
        
        /// <remarks/>
        Performance_Plan,
        
        /// <remarks/>
        Performance_Report,
    }
}
