//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace StratML.Core.Three {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class RatingType {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FiveLevelType", typeof(FiveLevelTypeType))]
        [System.Xml.Serialization.XmlElementAttribute("SevenLevelType", typeof(SevenLevelTypeType))]
        [System.Xml.Serialization.XmlElementAttribute("TenLevelType", typeof(TenLevelTypeType))]
        [System.Xml.Serialization.XmlElementAttribute("ThreeLevelType", typeof(ThreeLevelTypeType))]
        [System.Xml.Serialization.XmlElementAttribute("TwoLevelType", typeof(TwoLevelTypeType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("FiveLevelType", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public enum FiveLevelTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("SevenLevelType", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public enum SevenLevelTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("TenLevelType", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public enum TenLevelTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("ThreeLevelType", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public enum ThreeLevelTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("TwoLevelType", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public enum TwoLevelTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public partial class GoalType {
        
        private NameDescriptionType nameDescriptionField;
        
        private Place[] placeField;
        
        private Stakeholder[] stakeholderField;
        
        private AuthorityType[] authorityField;
        
        private SuccessFactor[] successFactorField;
        
        private OtherInformationType[] otherInformationField;
        
        private GoalTypePriority priorityField;
        
        private bool priorityFieldSpecified;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Place")]
        public Place[] Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Authority")]
        public AuthorityType[] Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SuccessFactor")]
        public SuccessFactor[] SuccessFactor {
            get {
                return this.successFactorField;
            }
            set {
                this.successFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherInformation")]
        public OtherInformationType[] OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public GoalTypePriority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("EconomicFactor", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class NameDescriptionType {
        
        private string sequenceIndicatorField;
        
        private string nameField;
        
        private string acronymField;
        
        private string descriptionField;
        
        private string[] identifierField;
        
        private string webAddressField;
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Acronym {
            get {
                return this.acronymField;
            }
            set {
                this.acronymField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Identifier")]
        public string[] Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string WebAddress {
            get {
                return this.webAddressField;
            }
            set {
                this.webAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class Place {
        
        private NameDescriptionType nameDescriptionField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class Stakeholder {
        
        private StakeholderType stakeholderTypeField;
        
        /// <remarks/>
        public StakeholderType StakeholderType {
            get {
                return this.stakeholderTypeField;
            }
            set {
                this.stakeholderTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class StakeholderType {
        
        private NameDescriptionType nameDescriptionField;
        
        private RoleType[] roleTypeField;
        
        private CategorizationType[] categorizationField;
        
        private ContactInformationType pointOfContactField;
        
        private StakeholderTypeStakeholderTypeType stakeholderTypeTypeField;
        
        private bool stakeholderTypeTypeFieldSpecified;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleType")]
        public RoleType[] RoleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categorization")]
        public CategorizationType[] Categorization {
            get {
                return this.categorizationField;
            }
            set {
                this.categorizationField = value;
            }
        }
        
        /// <remarks/>
        public ContactInformationType PointOfContact {
            get {
                return this.pointOfContactField;
            }
            set {
                this.pointOfContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StakeholderTypeStakeholderTypeType StakeholderTypeType {
            get {
                return this.stakeholderTypeTypeField;
            }
            set {
                this.stakeholderTypeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StakeholderTypeTypeSpecified {
            get {
                return this.stakeholderTypeTypeFieldSpecified;
            }
            set {
                this.stakeholderTypeTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class RoleType {
        
        private NameDescriptionType nameDescriptionField;
        
        private RoleTypePerformerOrBeneficiary performerOrBeneficiaryField;
        
        private bool performerOrBeneficiaryFieldSpecified;
        
        private RoleTypeRASCI rASCIField;
        
        private bool rASCIFieldSpecified;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RoleTypePerformerOrBeneficiary PerformerOrBeneficiary {
            get {
                return this.performerOrBeneficiaryField;
            }
            set {
                this.performerOrBeneficiaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerformerOrBeneficiarySpecified {
            get {
                return this.performerOrBeneficiaryFieldSpecified;
            }
            set {
                this.performerOrBeneficiaryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RoleTypeRASCI RASCI {
            get {
                return this.rASCIField;
            }
            set {
                this.rASCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RASCISpecified {
            get {
                return this.rASCIFieldSpecified;
            }
            set {
                this.rASCIFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum RoleTypePerformerOrBeneficiary {
        
        /// <remarks/>
        Performer,
        
        /// <remarks/>
        Beneficiary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum RoleTypeRASCI {
        
        /// <remarks/>
        Responsible,
        
        /// <remarks/>
        Accountable,
        
        /// <remarks/>
        Supportive,
        
        /// <remarks/>
        to_be_Consulted,
        
        /// <remarks/>
        to_be_Informed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("Categorization", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class CategorizationType {
        
        private string nameField;
        
        private CategoryType[] categoryField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category")]
        public CategoryType[] Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("Category", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class CategoryType {
        
        private string identifierField;
        
        private string nameField;
        
        private string webAddressField;
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string WebAddress {
            get {
                return this.webAddressField;
            }
            set {
                this.webAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("PointOfContact", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class ContactInformationType {
        
        private string identifierField;
        
        private string givenNameField;
        
        private string surnameField;
        
        private string phoneNumberField;
        
        private string emailAddressField;
        
        private string webAddressField;
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string WebAddress {
            get {
                return this.webAddressField;
            }
            set {
                this.webAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum StakeholderTypeStakeholderTypeType {
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        Organization,
        
        /// <remarks/>
        Generic_Group,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("Authority", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class AuthorityType {
        
        private NameDescriptionType nameDescriptionField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class SuccessFactor {
        
        private NameDescriptionType nameDescriptionField;
        
        private SuccessFactorCriticality criticalityField;
        
        private bool criticalityFieldSpecified;
        
        private SuccessFactorInternalOrExternal internalOrExternalField;
        
        private bool internalOrExternalFieldSpecified;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SuccessFactorCriticality Criticality {
            get {
                return this.criticalityField;
            }
            set {
                this.criticalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CriticalitySpecified {
            get {
                return this.criticalityFieldSpecified;
            }
            set {
                this.criticalityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SuccessFactorInternalOrExternal InternalOrExternal {
            get {
                return this.internalOrExternalField;
            }
            set {
                this.internalOrExternalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InternalOrExternalSpecified {
            get {
                return this.internalOrExternalFieldSpecified;
            }
            set {
                this.internalOrExternalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum SuccessFactorCriticality {
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        Contributory,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum SuccessFactorInternalOrExternal {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        External,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("OtherInformation", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class OtherInformationType {
        
        private NameDescriptionType nameDescriptionField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum GoalTypePriority {
        
        /// <remarks/>
        To_Be_Determined,
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class ActualResult {
        
        private string sequenceIndicatorField;
        
        private string descriptionField;
        
        private RatingType ratingTypeField;
        
        private decimal numberOfUnitsField;
        
        private bool numberOfUnitsFieldSpecified;
        
        private OtherInformationType[] otherInformationField;
        
        private string startDateField;
        
        private string startTimeField;
        
        private string endDateField;
        
        private string endTimeField;
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public RatingType RatingType {
            get {
                return this.ratingTypeField;
            }
            set {
                this.ratingTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal NumberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfUnitsSpecified {
            get {
                return this.numberOfUnitsFieldSpecified;
            }
            set {
                this.numberOfUnitsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherInformation")]
        public OtherInformationType[] OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("AdministrativeInformation", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class AdministrativeInformationType {
        
        private string identifierField;
        
        private string sourceField;
        
        private string startDateField;
        
        private string endDateField;
        
        private System.DateTime publicationDateField;
        
        private bool publicationDateFieldSpecified;
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="date")]
        public System.DateTime PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublicationDateSpecified {
            get {
                return this.publicationDateFieldSpecified;
            }
            set {
                this.publicationDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("Competency", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class CompetencyType {
        
        private NameDescriptionType nameDescriptionField;
        
        private CompetencyTypeCompetencyTypeType competencyTypeTypeField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CompetencyTypeCompetencyTypeType CompetencyTypeType {
            get {
                return this.competencyTypeTypeField;
            }
            set {
                this.competencyTypeTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum CompetencyTypeCompetencyTypeType {
        
        /// <remarks/>
        Core,
        
        /// <remarks/>
        Supporting,
        
        /// <remarks/>
        Ancillary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class DrivingForce {
        
        private NameDescriptionType nameDescriptionField;
        
        private DrivingForceInhibitingOrEnabling inhibitingOrEnablingField;
        
        private bool inhibitingOrEnablingFieldSpecified;
        
        private DrivingForceInternalOrExternal internalOrExternalField;
        
        private bool internalOrExternalFieldSpecified;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DrivingForceInhibitingOrEnabling InhibitingOrEnabling {
            get {
                return this.inhibitingOrEnablingField;
            }
            set {
                this.inhibitingOrEnablingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InhibitingOrEnablingSpecified {
            get {
                return this.inhibitingOrEnablingFieldSpecified;
            }
            set {
                this.inhibitingOrEnablingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DrivingForceInternalOrExternal InternalOrExternal {
            get {
                return this.internalOrExternalField;
            }
            set {
                this.internalOrExternalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InternalOrExternalSpecified {
            get {
                return this.internalOrExternalFieldSpecified;
            }
            set {
                this.internalOrExternalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum DrivingForceInhibitingOrEnabling {
        
        /// <remarks/>
        Enabling,
        
        /// <remarks/>
        Inhibiting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum DrivingForceInternalOrExternal {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        External,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class FunctionType {
        
        private NameDescriptionType nameDescriptionField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class Goal : GoalType {
        
        private ObjectiveType[] objectiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Objective")]
        public ObjectiveType[] Objective {
            get {
                return this.objectiveField;
            }
            set {
                this.objectiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("Objective", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class ObjectiveType {
        
        private NameDescriptionType nameDescriptionField;
        
        private Stakeholder[] stakeholderField;
        
        private CategorizationType[] categorizationField;
        
        private ManagementChallenge[] managementChallengeField;
        
        private OtherInformationType[] otherInformationField;
        
        private PerformanceIndicator[] performanceIndicatorField;
        
        private System.DateTime publicationDateField;
        
        private bool publicationDateFieldSpecified;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categorization")]
        public CategorizationType[] Categorization {
            get {
                return this.categorizationField;
            }
            set {
                this.categorizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManagementChallenge")]
        public ManagementChallenge[] ManagementChallenge {
            get {
                return this.managementChallengeField;
            }
            set {
                this.managementChallengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherInformation")]
        public OtherInformationType[] OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PerformanceIndicator")]
        public PerformanceIndicator[] PerformanceIndicator {
            get {
                return this.performanceIndicatorField;
            }
            set {
                this.performanceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="date")]
        public System.DateTime PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublicationDateSpecified {
            get {
                return this.publicationDateFieldSpecified;
            }
            set {
                this.publicationDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class ManagementChallenge {
        
        private NameDescriptionType nameDescriptionField;
        
        private ManagementChallengeProbability probabilityField;
        
        private ManagementChallengeImpact impactField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ManagementChallengeProbability Probability {
            get {
                return this.probabilityField;
            }
            set {
                this.probabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ManagementChallengeImpact Impact {
            get {
                return this.impactField;
            }
            set {
                this.impactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum ManagementChallengeProbability {
        
        /// <remarks/>
        To_Be_Determined,
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum ManagementChallengeImpact {
        
        /// <remarks/>
        To_Be_Determined,
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class PerformanceIndicator {
        
        private string sequenceIndicatorField;
        
        private string measurementDimensionField;
        
        private string unitOfMeasurementField;
        
        private string identifierField;
        
        private Relationship[] relationshipField;
        
        private MeasurementInstance[] measurementInstanceField;
        
        private CategorizationType[] categorizationField;
        
        private OtherInformationType[] otherInformationField;
        
        private ValueChainStageType valueChainStageField;
        
        private bool valueChainStageFieldSpecified;
        
        private PerformanceIndicatorTypeType performanceIndicatorTypeField;
        
        private bool performanceIndicatorTypeFieldSpecified;
        
        private PerformanceIndicatorKeyness keynessField;
        
        private bool keynessFieldSpecified;
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string MeasurementDimension {
            get {
                return this.measurementDimensionField;
            }
            set {
                this.measurementDimensionField = value;
            }
        }
        
        /// <remarks/>
        public string UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MeasurementInstance")]
        public MeasurementInstance[] MeasurementInstance {
            get {
                return this.measurementInstanceField;
            }
            set {
                this.measurementInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categorization")]
        public CategorizationType[] Categorization {
            get {
                return this.categorizationField;
            }
            set {
                this.categorizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherInformation")]
        public OtherInformationType[] OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueChainStageType ValueChainStage {
            get {
                return this.valueChainStageField;
            }
            set {
                this.valueChainStageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueChainStageSpecified {
            get {
                return this.valueChainStageFieldSpecified;
            }
            set {
                this.valueChainStageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PerformanceIndicatorTypeType PerformanceIndicatorType {
            get {
                return this.performanceIndicatorTypeField;
            }
            set {
                this.performanceIndicatorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerformanceIndicatorTypeSpecified {
            get {
                return this.performanceIndicatorTypeFieldSpecified;
            }
            set {
                this.performanceIndicatorTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PerformanceIndicatorKeyness Keyness {
            get {
                return this.keynessField;
            }
            set {
                this.keynessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeynessSpecified {
            get {
                return this.keynessFieldSpecified;
            }
            set {
                this.keynessFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class Relationship {
        
        private NameDescriptionType nameDescriptionField;
        
        private RelationshipReferent[] referentField;
        
        private RelationshipTypeType relationshipTypeField;
        
        private bool relationshipTypeFieldSpecified;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Referent")]
        public RelationshipReferent[] Referent {
            get {
                return this.referentField;
            }
            set {
                this.referentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RelationshipTypeType RelationshipType {
            get {
                return this.relationshipTypeField;
            }
            set {
                this.relationshipTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelationshipTypeSpecified {
            get {
                return this.relationshipTypeFieldSpecified;
            }
            set {
                this.relationshipTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public partial class RelationshipReferent {
        
        private NameDescriptionType nameDescriptionField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum RelationshipTypeType {
        
        /// <remarks/>
        Broader_Than,
        
        /// <remarks/>
        Peer_To,
        
        /// <remarks/>
        Narrower_Than,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class MeasurementInstance {
        
        private TargetResult[] targetResultField;
        
        private ActualResult[] actualResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetResult")]
        public TargetResult[] TargetResult {
            get {
                return this.targetResultField;
            }
            set {
                this.targetResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActualResult")]
        public ActualResult[] ActualResult {
            get {
                return this.actualResultField;
            }
            set {
                this.actualResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class TargetResult {
        
        private string sequenceIndicatorField;
        
        private string descriptionField;
        
        private decimal numberOfUnitsField;
        
        private bool numberOfUnitsFieldSpecified;
        
        private OtherInformationType[] otherInformationField;
        
        private string startDateField;
        
        private string startTimeField;
        
        private string endDateField;
        
        private string endTimeField;
        
        private string weightingField;
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal NumberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfUnitsSpecified {
            get {
                return this.numberOfUnitsFieldSpecified;
            }
            set {
                this.numberOfUnitsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherInformation")]
        public OtherInformationType[] OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string EndTime {
            get {
                return this.endTimeField;
            }
            set {
                this.endTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Weighting {
            get {
                return this.weightingField;
            }
            set {
                this.weightingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum ValueChainStageType {
        
        /// <remarks/>
        Outcome,
        
        /// <remarks/>
        Output_Processing,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        Input_Processing,
        
        /// <remarks/>
        Input,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum PerformanceIndicatorTypeType {
        
        /// <remarks/>
        Quantitative,
        
        /// <remarks/>
        Qualitative,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum PerformanceIndicatorKeyness {
        
        /// <remarks/>
        To_Be_Determined,
        
        /// <remarks/>
        Key,
        
        /// <remarks/>
        Secondary,
        
        /// <remarks/>
        Ancillary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class Mission {
        
        private string descriptionField;
        
        private string identifierField;
        
        private FunctionType[] functionTypeField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FunctionType")]
        public FunctionType[] FunctionType {
            get {
                return this.functionTypeField;
            }
            set {
                this.functionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class Organization {
        
        private NameDescriptionType nameDescriptionField;
        
        private Stakeholder[] stakeholderField;
        
        private CompetencyType[] competencyField;
        
        private ValuePropositionType[] valuePropositionField;
        
        private SpecialOrganizationType specialOrganizationTypeField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Competency")]
        public CompetencyType[] Competency {
            get {
                return this.competencyField;
            }
            set {
                this.competencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueProposition")]
        public ValuePropositionType[] ValueProposition {
            get {
                return this.valuePropositionField;
            }
            set {
                this.valuePropositionField = value;
            }
        }
        
        /// <remarks/>
        public SpecialOrganizationType SpecialOrganizationType {
            get {
                return this.specialOrganizationTypeField;
            }
            set {
                this.specialOrganizationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute("ValueProposition", Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class ValuePropositionType {
        
        private NameDescriptionType nameDescriptionField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class SpecialOrganizationType {
        
        private string otherOrganizationTypeNameField;
        
        private SpecialOrganizationTypeType valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherOrganizationTypeName {
            get {
                return this.otherOrganizationTypeNameField;
            }
            set {
                this.otherOrganizationTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public SpecialOrganizationTypeType Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum SpecialOrganizationTypeType {
        
        /// <remarks/>
        Board_of_Directors,
        
        /// <remarks/>
        Committee,
        
        /// <remarks/>
        Conference,
        
        /// <remarks/>
        Consortium,
        
        /// <remarks/>
        Cooperative,
        
        /// <remarks/>
        Exposition,
        
        /// <remarks/>
        Family,
        
        /// <remarks/>
        Individual,
        
        /// <remarks/>
        Initiative,
        
        /// <remarks/>
        Investment,
        
        /// <remarks/>
        Program,
        
        /// <remarks/>
        Project,
        
        /// <remarks/>
        Student,
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        Virtual,
        
        /// <remarks/>
        Work_Group,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class PESTLE {
        
        private NameDescriptionType[] politicalFactorField;
        
        private NameDescriptionType[] economicFactorField;
        
        private NameDescriptionType[] socialFactorField;
        
        private NameDescriptionType[] technologicalFactorField;
        
        private NameDescriptionType[] legalFactorField;
        
        private NameDescriptionType[] environmentalFactorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PoliticalFactor")]
        public NameDescriptionType[] PoliticalFactor {
            get {
                return this.politicalFactorField;
            }
            set {
                this.politicalFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EconomicFactor")]
        public NameDescriptionType[] EconomicFactor {
            get {
                return this.economicFactorField;
            }
            set {
                this.economicFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SocialFactor")]
        public NameDescriptionType[] SocialFactor {
            get {
                return this.socialFactorField;
            }
            set {
                this.socialFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TechnologicalFactor")]
        public NameDescriptionType[] TechnologicalFactor {
            get {
                return this.technologicalFactorField;
            }
            set {
                this.technologicalFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LegalFactor")]
        public NameDescriptionType[] LegalFactor {
            get {
                return this.legalFactorField;
            }
            set {
                this.legalFactorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EnvironmentalFactor")]
        public NameDescriptionType[] EnvironmentalFactor {
            get {
                return this.environmentalFactorField;
            }
            set {
                this.environmentalFactorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class StrategyFramework {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DrivingForce", typeof(DrivingForce))]
        [System.Xml.Serialization.XmlElementAttribute("PESTLE", typeof(PESTLE))]
        [System.Xml.Serialization.XmlElementAttribute("SWOT", typeof(SWOT))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class SWOT {
        
        private NameDescriptionType[] strengthField;
        
        private NameDescriptionType[] weaknessField;
        
        private NameDescriptionType[] opportunityField;
        
        private NameDescriptionType[] threatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Strength")]
        public NameDescriptionType[] Strength {
            get {
                return this.strengthField;
            }
            set {
                this.strengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Weakness")]
        public NameDescriptionType[] Weakness {
            get {
                return this.weaknessField;
            }
            set {
                this.weaknessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Opportunity")]
        public NameDescriptionType[] Opportunity {
            get {
                return this.opportunityField;
            }
            set {
                this.opportunityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Threat")]
        public NameDescriptionType[] Threat {
            get {
                return this.threatField;
            }
            set {
                this.threatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class Value {
        
        private NameDescriptionType nameDescriptionField;
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class Vision {
        
        private string descriptionField;
        
        private string identifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements", IsNullable=false)]
    public partial class PerformancePlanOrReport {
        
        private NameDescriptionType nameDescriptionField;
        
        private Organization[] organizationField;
        
        private Vision visionField;
        
        private Mission missionField;
        
        private Value[] valueField;
        
        private Goal[] goalField;
        
        private StrategyFramework[] strategyFrameworkField;
        
        private OtherInformationType[] otherInformationField;
        
        private AdministrativeInformationType administrativeInformationField;
        
        private ContactInformationType submitterField;
        
        private PerformancePlanOrReportDocumentType documentTypeField;
        
        private PerformancePlanOrReportLanguage languageField;
        
        public PerformancePlanOrReport() {
            this.languageField = PerformancePlanOrReportLanguage.en;
        }
        
        /// <remarks/>
        public NameDescriptionType NameDescription {
            get {
                return this.nameDescriptionField;
            }
            set {
                this.nameDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization")]
        public Organization[] Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public Vision Vision {
            get {
                return this.visionField;
            }
            set {
                this.visionField = value;
            }
        }
        
        /// <remarks/>
        public Mission Mission {
            get {
                return this.missionField;
            }
            set {
                this.missionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public Value[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Goal")]
        public Goal[] Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StrategyFramework")]
        public StrategyFramework[] StrategyFramework {
            get {
                return this.strategyFrameworkField;
            }
            set {
                this.strategyFrameworkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherInformation")]
        public OtherInformationType[] OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        public AdministrativeInformationType AdministrativeInformation {
            get {
                return this.administrativeInformationField;
            }
            set {
                this.administrativeInformationField = value;
            }
        }
        
        /// <remarks/>
        public ContactInformationType Submitter {
            get {
                return this.submitterField;
            }
            set {
                this.submitterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PerformancePlanOrReportDocumentType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(PerformancePlanOrReportLanguage.en)]
        public PerformancePlanOrReportLanguage Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum PerformancePlanOrReportDocumentType {
        
        /// <remarks/>
        Strategic_Plan,
        
        /// <remarks/>
        Performance_Plan,
        
        /// <remarks/>
        Performance_Report,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas:AIIM:org:03201408:AdditionalElements")]
    public enum PerformancePlanOrReportLanguage {
        
        /// <remarks/>
        en,
        
        /// <remarks/>
        es,
        
        /// <remarks/>
        de,
        
        /// <remarks/>
        fr,
        
        /// <remarks/>
        it,
        
        /// <remarks/>
        ja,
        
        /// <remarks/>
        pt,
        
        /// <remarks/>
        ru,
        
        /// <remarks/>
        zh,
    }
}
