//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace StratML.Core.One {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute("AdministrativeInformation", Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class AdministrativeInformationType {
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private System.DateTime publicationDateField;
        
        private bool publicationDateFieldSpecified;
        
        private string sourceField;
        
        private ContactInformationType submitterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublicationDateSpecified {
            get {
                return this.publicationDateFieldSpecified;
            }
            set {
                this.publicationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public ContactInformationType Submitter {
            get {
                return this.submitterField;
            }
            set {
                this.submitterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute("Submitter", Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class ContactInformationType {
        
        private string givenNameField;
        
        private string surnameField;
        
        private string phoneNumberField;
        
        private string emailAddressField;
        
        /// <remarks/>
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class Goal {
        
        private string nameField;
        
        private string descriptionField;
        
        private string identifierField;
        
        private string sequenceIndicatorField;
        
        private Stakeholder[] stakeholderField;
        
        private string otherInformationField;
        
        private Objective[] objectiveField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Objective")]
        public Objective[] Objective {
            get {
                return this.objectiveField;
            }
            set {
                this.objectiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class Stakeholder {
        
        private string nameField;
        
        private string descriptionField;
        
        private StakeholderStakeholderTypeType stakeholderTypeTypeField;
        
        private bool stakeholderTypeTypeFieldSpecified;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StakeholderStakeholderTypeType StakeholderTypeType {
            get {
                return this.stakeholderTypeTypeField;
            }
            set {
                this.stakeholderTypeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StakeholderTypeTypeSpecified {
            get {
                return this.stakeholderTypeTypeFieldSpecified;
            }
            set {
                this.stakeholderTypeTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    public enum StakeholderStakeholderTypeType {
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        Organization,
        
        /// <remarks/>
        Generic_Group,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class Objective {
        
        private string nameField;
        
        private string descriptionField;
        
        private string identifierField;
        
        private string sequenceIndicatorField;
        
        private Stakeholder[] stakeholderField;
        
        private string otherInformationField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class Mission {
        
        private string descriptionField;
        
        private string identifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class Organization {
        
        private string nameField;
        
        private string acronymField;
        
        private string identifierField;
        
        private string descriptionField;
        
        private Stakeholder[] stakeholderField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Acronym {
            get {
                return this.acronymField;
            }
            set {
                this.acronymField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class StrategicPlan {
        
        private string nameField;
        
        private string descriptionField;
        
        private string otherInformationField;
        
        private StrategicPlanCore strategicPlanCoreField;
        
        private AdministrativeInformationType administrativeInformationField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        public StrategicPlanCore StrategicPlanCore {
            get {
                return this.strategicPlanCoreField;
            }
            set {
                this.strategicPlanCoreField = value;
            }
        }
        
        /// <remarks/>
        public AdministrativeInformationType AdministrativeInformation {
            get {
                return this.administrativeInformationField;
            }
            set {
                this.administrativeInformationField = value;
            }
        }
        [XmlIgnore]
        public string id { get; set; }
        [XmlIgnore]
        public string organizationNameCollection { get; set; }
        [XmlIgnore]
        public string organizationAcronymCollection { get; set; }
        [XmlIgnore]
        public string organizationDescriptionCollection { get; set; }
        [XmlIgnore]
        public string stakeholderNameCollection { get; set; }
        [XmlIgnore]
        public string stakeholderDescriptionCollection { get; set; }
        [XmlIgnore]
        public string valueNameCollection { get; set; }
        [XmlIgnore]
        public string valueDescriptionCollection { get; set; }
        [XmlIgnore]
        public string goalNameCollection { get; set; }
        [XmlIgnore]
        public string goalDescriptionCollection { get; set; }
        [XmlIgnore]
        public string goalOtherInformationCollection { get; set; }
        [XmlIgnore]
        public string objectiveNameCollection { get; set; }
        [XmlIgnore]
        public string objectiveDescriptionCollection { get; set; }
        public string objectiveOtherInformationCollection { get; set; }

    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class StrategicPlanCore {
        
        private Organization[] organizationField;
        
        private Vision visionField;
        
        private Mission missionField;
        
        private Value[] valueField;
        
        private Goal[] goalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization")]
        public Organization[] Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public Vision Vision {
            get {
                return this.visionField;
            }
            set {
                this.visionField = value;
            }
        }
        
        /// <remarks/>
        public Mission Mission {
            get {
                return this.missionField;
            }
            set {
                this.missionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public Value[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Goal")]
        public Goal[] Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class Vision {
        
        private string descriptionField;
        
        private string identifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:stratml_core", IsNullable=false)]
    public partial class Value {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
}
