//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace StratML.Core.ThreeFive {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.stratml.us/3.5", IsNullable=false)]
    public partial class OrganizationalStrategyDocument : Strategy {
        
        private Organization organizationField;
        
        private Person submitterField;
        
        private AdministrativeInformationType administrativeInformationField;
        
        /// <remarks/>
        public Organization Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public Person Submitter {
            get {
                return this.submitterField;
            }
            set {
                this.submitterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
        public AdministrativeInformationType AdministrativeInformation {
            get {
                return this.administrativeInformationField;
            }
            set {
                this.administrativeInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderOrganization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Organization : Group {
        
        private Strategy strategyField;
        
        private Organization[] organization1Field;
        
        /// <remarks/>
        public Strategy Strategy {
            get {
                return this.strategyField;
            }
            set {
                this.strategyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization")]
        public Organization[] Organization1 {
            get {
                return this.organization1Field;
            }
            set {
                this.organization1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Strategy : NameIdentifier {
        
        private Mission missionField;
        
        private Vision visionField;
        
        private Value[] valueField;
        
        private Goal[] goalField;
        
        private DrivingForce drivingForceField;
        
        private StrategyFramework[] frameworkField;
        
        /// <remarks/>
        public Mission Mission {
            get {
                return this.missionField;
            }
            set {
                this.missionField = value;
            }
        }
        
        /// <remarks/>
        public Vision Vision {
            get {
                return this.visionField;
            }
            set {
                this.visionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public Value[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Goal")]
        public Goal[] Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
        
        /// <remarks/>
        public DrivingForce DrivingForce {
            get {
                return this.drivingForceField;
            }
            set {
                this.drivingForceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Framework")]
        public StrategyFramework[] Framework {
            get {
                return this.frameworkField;
            }
            set {
                this.frameworkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Mission : Artifact {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Goal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PerformanceIndicator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Objective))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Vision))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mission))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Artifact : NameIdentifier {
        
        private string sequenceIndicatorField;
        
        private StakeholderPerson[] stakeholderPersonField;
        
        private StakeholderOrganization[] stakeholderOrganizationField;
        
        private StakeholderGroup[] stakeholderGroupField;
        
        private string otherInformationField;
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StakeholderPerson")]
        public StakeholderPerson[] StakeholderPerson {
            get {
                return this.stakeholderPersonField;
            }
            set {
                this.stakeholderPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StakeholderOrganization")]
        public StakeholderOrganization[] StakeholderOrganization {
            get {
                return this.stakeholderOrganizationField;
            }
            set {
                this.stakeholderOrganizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StakeholderGroup")]
        public StakeholderGroup[] StakeholderGroup {
            get {
                return this.stakeholderGroupField;
            }
            set {
                this.stakeholderGroupField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class StakeholderPerson : Person {
        
        private Relationship[] relationshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Relationship : NameIdentifier {
        
        private string[] referentIdentifierField;
        
        private string relationshipTypeField;
        
        public Relationship() {
            this.relationshipTypeField = "Peer_To";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferentIdentifier", DataType="ID")]
        public string[] ReferentIdentifier {
            get {
                return this.referentIdentifierField;
            }
            set {
                this.referentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Peer_To")]
        public string RelationshipType {
            get {
                return this.relationshipTypeField;
            }
            set {
                this.relationshipTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StrategyFramework))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DrivingForce))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuccessFactor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManagementChallenge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Category))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CategoryGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Relationship))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Role))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactMechanism))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Email))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhysicalAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Actor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderOrganization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Person))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderPerson))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Authority))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Artifact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Goal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PerformanceIndicator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Objective))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Vision))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mission))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Strategy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Map))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class NameIdentifier {
        
        private string identiferField;
        
        private string nameField;
        
        private string descriptionField;
        
        private Map[] mapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifer {
            get {
                return this.identiferField;
            }
            set {
                this.identiferField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Map")]
        public Map[] Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Map : NameIdentifier {
        
        private MapType typeField;
        
        private double weightField;
        
        private System.DateTime publicationDateField;
        
        private bool publicationDateFieldSpecified;
        
        private string[] mappedIdentifierField;
        
        public Map() {
            this.typeField = MapType.Relationship;
            this.weightField = 1D;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(MapType.Relationship)]
        public MapType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublicationDateSpecified {
            get {
                return this.publicationDateFieldSpecified;
            }
            set {
                this.publicationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MappedIdentifier", DataType="ID")]
        public string[] MappedIdentifier {
            get {
                return this.mappedIdentifierField;
            }
            set {
                this.mappedIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum MapType {
        
        /// <remarks/>
        Relationship,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        Supports,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("AdministrativeInformation", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class AdministrativeInformationType {
        
        private string identifierField;
        
        private string startDateField;
        
        private string endDateField;
        
        private string publicationDateField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasurementResultDescriptor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasurementResultUnits))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResult {
        
        private string identifierField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResultDescriptor : MeasurementResult {
        
        private MeasurementResultDescriptorDescriptor descriptorField;
        
        /// <remarks/>
        public MeasurementResultDescriptorDescriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResultDescriptorDescriptor {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResultUnits : MeasurementResult {
        
        private double numberOfUnitsField;
        
        /// <remarks/>
        public double NumberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class ContactInformation {
        
        private string identifierField;
        
        private PhoneNumber[] phoneNumberField;
        
        private Email[] emailAddressField;
        
        private PhysicalAddress[] addressField;
        
        private WebAddress[] websiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhoneNumber")]
        public PhoneNumber[] PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailAddress")]
        public Email[] EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address")]
        public PhysicalAddress[] Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Website")]
        public WebAddress[] Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class PhoneNumber : ContactMechanism {
        
        private string numberField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Email))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhysicalAddress))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class ContactMechanism : NameIdentifier {
        
        private string typeField;
        
        public ContactMechanism() {
            this.typeField = "Primary";
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class WebAddress : ContactMechanism {
        
        private string webAddress1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WebAddress")]
        public string WebAddress1 {
            get {
                return this.webAddress1Field;
            }
            set {
                this.webAddress1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Email : ContactMechanism {
        
        private string email1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class PhysicalAddress : ContactMechanism {
        
        private string addressLabelField;
        
        private string streetField;
        
        private string localityField;
        
        private string regionField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string pOBoxField;
        
        private string extendedAddressField;
        
        /// <remarks/>
        public string AddressLabel {
            get {
                return this.addressLabelField;
            }
            set {
                this.addressLabelField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string POBox {
            get {
                return this.pOBoxField;
            }
            set {
                this.pOBoxField = value;
            }
        }
        
        /// <remarks/>
        public string ExtendedAddress {
            get {
                return this.extendedAddressField;
            }
            set {
                this.extendedAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class StrategyFramework : NameIdentifier {
        
        private System.Xml.XmlElement dataField;
        
        /// <remarks/>
        public System.Xml.XmlElement Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class DrivingForce : NameIdentifier {
        
        private InhibitingOrEnabling inhibitingOrEnablingField;
        
        private InternalOrExternal internalOrExternalField;
        
        /// <remarks/>
        public InhibitingOrEnabling InhibitingOrEnabling {
            get {
                return this.inhibitingOrEnablingField;
            }
            set {
                this.inhibitingOrEnablingField = value;
            }
        }
        
        /// <remarks/>
        public InternalOrExternal InternalOrExternal {
            get {
                return this.internalOrExternalField;
            }
            set {
                this.internalOrExternalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum InhibitingOrEnabling {
        
        /// <remarks/>
        Enabling,
        
        /// <remarks/>
        Inhibiting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum InternalOrExternal {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        External,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class SuccessFactor : NameIdentifier {
        
        private Criticality criticalityField;
        
        private InternalOrExternal internalOrExternalField;
        
        /// <remarks/>
        public Criticality Criticality {
            get {
                return this.criticalityField;
            }
            set {
                this.criticalityField = value;
            }
        }
        
        /// <remarks/>
        public InternalOrExternal InternalOrExternal {
            get {
                return this.internalOrExternalField;
            }
            set {
                this.internalOrExternalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum Criticality {
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        Contributory,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class ManagementChallenge : NameIdentifier {
        
        private Priority probabilityField;
        
        private Priority impactField;
        
        /// <remarks/>
        public Priority Probability {
            get {
                return this.probabilityField;
            }
            set {
                this.probabilityField = value;
            }
        }
        
        /// <remarks/>
        public Priority Impact {
            get {
                return this.impactField;
            }
            set {
                this.impactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum Priority {
        
        /// <remarks/>
        To_Be_Determined,
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Category : NameIdentifier {
        
        private WebAddress websiteField;
        
        /// <remarks/>
        public WebAddress Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class CategoryGroup : NameIdentifier {
        
        private Category[] categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category")]
        public Category[] Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Role : NameIdentifier {
        
        private RoleType roleTypeField;
        
        private bool roleTypeFieldSpecified;
        
        /// <remarks/>
        public RoleType RoleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoleTypeSpecified {
            get {
                return this.roleTypeFieldSpecified;
            }
            set {
                this.roleTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum RoleType {
        
        /// <remarks/>
        Performer,
        
        /// <remarks/>
        Beneficiary,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderOrganization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Person))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderPerson))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Authority))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Actor : NameIdentifier {
        
        private ContactInformation contactField;
        
        private Role[] roleField;
        
        /// <remarks/>
        public ContactInformation Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Role")]
        public Role[] Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderOrganization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Group : Actor {
        
        private Person[] personField;
        
        private string acronymField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Person")]
        public Person[] Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public string Acronym {
            get {
                return this.acronymField;
            }
            set {
                this.acronymField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StakeholderPerson))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Person : Actor {
        
        private string givenNameField;
        
        private string surnameField;
        
        /// <remarks/>
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class StakeholderGroup : Group {
        
        private Relationship[] relationshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Authority : Actor {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class StakeholderOrganization : Organization {
        
        private Relationship[] relationshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Goal : Artifact {
        
        private Objective[] objectiveField;
        
        private Authority[] authorityField;
        
        private PhysicalAddress placeField;
        
        private SuccessFactor successFactorField;
        
        private Priority priorityField;
        
        private bool priorityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Objective")]
        public Objective[] Objective {
            get {
                return this.objectiveField;
            }
            set {
                this.objectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Authority")]
        public Authority[] Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public PhysicalAddress Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        public SuccessFactor SuccessFactor {
            get {
                return this.successFactorField;
            }
            set {
                this.successFactorField = value;
            }
        }
        
        /// <remarks/>
        public Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Objective : Artifact {
        
        private CategoryGroup[] categorizationField;
        
        private ManagementChallenge[] managementChallengeField;
        
        private PerformanceIndicator[] performanceIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categorization")]
        public CategoryGroup[] Categorization {
            get {
                return this.categorizationField;
            }
            set {
                this.categorizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManagementChallenge")]
        public ManagementChallenge[] ManagementChallenge {
            get {
                return this.managementChallengeField;
            }
            set {
                this.managementChallengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PerformanceIndicator")]
        public PerformanceIndicator[] PerformanceIndicator {
            get {
                return this.performanceIndicatorField;
            }
            set {
                this.performanceIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class PerformanceIndicator : Artifact {
        
        private NameIdentifier measurementDimensionField;
        
        private NameIdentifier unitOfMeasurementField;
        
        private PerformanceIndicatorTargetResults targetResultsField;
        
        private PerformanceIndicatorActualResults actualResultsField;
        
        private CategoryGroup[] categorizationField;
        
        private Keyness keynessField;
        
        private bool keynessFieldSpecified;
        
        private ValueChainStageType valueChainStageField;
        
        private bool valueChainStageFieldSpecified;
        
        /// <remarks/>
        public NameIdentifier MeasurementDimension {
            get {
                return this.measurementDimensionField;
            }
            set {
                this.measurementDimensionField = value;
            }
        }
        
        /// <remarks/>
        public NameIdentifier UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        public PerformanceIndicatorTargetResults TargetResults {
            get {
                return this.targetResultsField;
            }
            set {
                this.targetResultsField = value;
            }
        }
        
        /// <remarks/>
        public PerformanceIndicatorActualResults ActualResults {
            get {
                return this.actualResultsField;
            }
            set {
                this.actualResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categorization")]
        public CategoryGroup[] Categorization {
            get {
                return this.categorizationField;
            }
            set {
                this.categorizationField = value;
            }
        }
        
        /// <remarks/>
        public Keyness Keyness {
            get {
                return this.keynessField;
            }
            set {
                this.keynessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeynessSpecified {
            get {
                return this.keynessFieldSpecified;
            }
            set {
                this.keynessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ValueChainStageType ValueChainStage {
            get {
                return this.valueChainStageField;
            }
            set {
                this.valueChainStageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueChainStageSpecified {
            get {
                return this.valueChainStageFieldSpecified;
            }
            set {
                this.valueChainStageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    public partial class PerformanceIndicatorTargetResults {
        
        private MeasurementResultUnits[] unitResultField;
        
        private MeasurementResultDescriptor[] descriptorResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnitResult")]
        public MeasurementResultUnits[] UnitResult {
            get {
                return this.unitResultField;
            }
            set {
                this.unitResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DescriptorResult")]
        public MeasurementResultDescriptor[] DescriptorResult {
            get {
                return this.descriptorResultField;
            }
            set {
                this.descriptorResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    public partial class PerformanceIndicatorActualResults {
        
        private MeasurementResultUnits[] unitResultField;
        
        private MeasurementResultDescriptor[] descriptorResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnitResult")]
        public MeasurementResultUnits[] UnitResult {
            get {
                return this.unitResultField;
            }
            set {
                this.unitResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DescriptorResult")]
        public MeasurementResultDescriptor[] DescriptorResult {
            get {
                return this.descriptorResultField;
            }
            set {
                this.descriptorResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum Keyness {
        
        /// <remarks/>
        To_Be_Determined,
        
        /// <remarks/>
        Key,
        
        /// <remarks/>
        Secondary,
        
        /// <remarks/>
        Ancillary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum ValueChainStageType {
        
        /// <remarks/>
        Outcome,
        
        /// <remarks/>
        Output_Processing,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        Input_Processing,
        
        /// <remarks/>
        Input,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Value : Artifact {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Vision : Artifact {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class PerformancePlanOrReport {
        
        private string nameField;
        
        private string descriptionField;
        
        private string otherInformationField;
        
        private StrategicPlanCore strategicPlanCoreField;
        
        private AdministrativeInformationType administrativeInformationField;
        
        private ContactInformationType submitterField;
        
        private PerformancePlanOrReportType typeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        public StrategicPlanCore StrategicPlanCore {
            get {
                return this.strategicPlanCoreField;
            }
            set {
                this.strategicPlanCoreField = value;
            }
        }
        
        /// <remarks/>
        public AdministrativeInformationType AdministrativeInformation {
            get {
                return this.administrativeInformationField;
            }
            set {
                this.administrativeInformationField = value;
            }
        }
        
        /// <remarks/>
        public ContactInformationType Submitter {
            get {
                return this.submitterField;
            }
            set {
                this.submitterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PerformancePlanOrReportType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class StrategicPlanCore {
        
        private Organization1[] organizationField;
        
        private Vision1 visionField;
        
        private Mission1 missionField;
        
        private Value1[] valueField;
        
        private Goal1[] goalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization")]
        public Organization1[] Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public Vision1 Vision {
            get {
                return this.visionField;
            }
            set {
                this.visionField = value;
            }
        }
        
        /// <remarks/>
        public Mission1 Mission {
            get {
                return this.missionField;
            }
            set {
                this.missionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public Value1[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Goal")]
        public Goal1[] Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Organization", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Organization1 {
        
        private string nameField;
        
        private string acronymField;
        
        private string identifierField;
        
        private string descriptionField;
        
        private Stakeholder[] stakeholderField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Acronym {
            get {
                return this.acronymField;
            }
            set {
                this.acronymField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Stakeholder {
        
        private string nameField;
        
        private string descriptionField;
        
        private Role1[] roleField;
        
        private StakeholderStakeholderTypeType stakeholderTypeTypeField;
        
        private bool stakeholderTypeTypeFieldSpecified;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Role")]
        public Role1[] Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public StakeholderStakeholderTypeType StakeholderTypeType {
            get {
                return this.stakeholderTypeTypeField;
            }
            set {
                this.stakeholderTypeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StakeholderTypeTypeSpecified {
            get {
                return this.stakeholderTypeTypeFieldSpecified;
            }
            set {
                this.stakeholderTypeTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Role", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Role1 {
        
        private string nameField;
        
        private string descriptionField;
        
        private RoleType1[] roleTypeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleType")]
        public RoleType1[] RoleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("RoleType", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public enum RoleType1 {
        
        /// <remarks/>
        Performer,
        
        /// <remarks/>
        Beneficiary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum StakeholderStakeholderTypeType {
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        Organization,
        
        /// <remarks/>
        Generic_Group,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Vision", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Vision1 {
        
        private string descriptionField;
        
        private string identifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Mission", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Mission1 {
        
        private string descriptionField;
        
        private string identifierField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Value", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Value1 {
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Goal", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Goal1 : GoalType {
        
        private ObjectiveType[] objectiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Objective")]
        public ObjectiveType[] Objective {
            get {
                return this.objectiveField;
            }
            set {
                this.objectiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Objective", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class ObjectiveType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string identifierField;
        
        private string sequenceIndicatorField;
        
        private Stakeholder[] stakeholderField;
        
        private string otherInformationField;
        
        private PerformanceIndicator1[] performanceIndicatorField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PerformanceIndicator")]
        public PerformanceIndicator1[] PerformanceIndicator {
            get {
                return this.performanceIndicatorField;
            }
            set {
                this.performanceIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("PerformanceIndicator", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class PerformanceIndicator1 {
        
        private string sequenceIndicatorField;
        
        private string measurementDimensionField;
        
        private string unitOfMeasurementField;
        
        private string identifierField;
        
        private Relationship1[] relationshipField;
        
        private MeasurementInstance[] measurementInstanceField;
        
        private string otherInformationField;
        
        private ValueChainStageType1 valueChainStageField;
        
        private bool valueChainStageFieldSpecified;
        
        private PerformanceIndicatorTypeType performanceIndicatorTypeField;
        
        private bool performanceIndicatorTypeFieldSpecified;
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        public string MeasurementDimension {
            get {
                return this.measurementDimensionField;
            }
            set {
                this.measurementDimensionField = value;
            }
        }
        
        /// <remarks/>
        public string UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship1[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MeasurementInstance")]
        public MeasurementInstance[] MeasurementInstance {
            get {
                return this.measurementInstanceField;
            }
            set {
                this.measurementInstanceField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueChainStageType1 ValueChainStage {
            get {
                return this.valueChainStageField;
            }
            set {
                this.valueChainStageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueChainStageSpecified {
            get {
                return this.valueChainStageFieldSpecified;
            }
            set {
                this.valueChainStageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PerformanceIndicatorTypeType PerformanceIndicatorType {
            get {
                return this.performanceIndicatorTypeField;
            }
            set {
                this.performanceIndicatorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PerformanceIndicatorTypeSpecified {
            get {
                return this.performanceIndicatorTypeFieldSpecified;
            }
            set {
                this.performanceIndicatorTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Relationship", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Relationship1 {
        
        private string identifierField;
        
        private string[] referentIdentifierField;
        
        private string nameField;
        
        private string descriptionField;
        
        private RelationshipTypeType relationshipTypeField;
        
        private bool relationshipTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferentIdentifier")]
        public string[] ReferentIdentifier {
            get {
                return this.referentIdentifierField;
            }
            set {
                this.referentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public RelationshipTypeType RelationshipType {
            get {
                return this.relationshipTypeField;
            }
            set {
                this.relationshipTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelationshipTypeSpecified {
            get {
                return this.relationshipTypeFieldSpecified;
            }
            set {
                this.relationshipTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum RelationshipTypeType {
        
        /// <remarks/>
        Broader_Than,
        
        /// <remarks/>
        Peer_To,
        
        /// <remarks/>
        Narrower_Than,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class MeasurementInstance {
        
        private TargetResult[] targetResultField;
        
        private ActualResult[] actualResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TargetResult")]
        public TargetResult[] TargetResult {
            get {
                return this.targetResultField;
            }
            set {
                this.targetResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActualResult")]
        public ActualResult[] ActualResult {
            get {
                return this.actualResultField;
            }
            set {
                this.actualResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class TargetResult {
        
        private string startDateField;
        
        private string endDateField;
        
        private string numberOfUnitsField;
        
        private Descriptor descriptorField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string NumberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
            }
        }
        
        /// <remarks/>
        public Descriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class Descriptor {
        
        private string descriptorNameField;
        
        private string descriptorValueField;
        
        /// <remarks/>
        public string DescriptorName {
            get {
                return this.descriptorNameField;
            }
            set {
                this.descriptorNameField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptorValue {
            get {
                return this.descriptorValueField;
            }
            set {
                this.descriptorValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class ActualResult {
        
        private string startDateField;
        
        private string endDateField;
        
        private string numberOfUnitsField;
        
        private Descriptor descriptorField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        public string NumberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
            }
        }
        
        /// <remarks/>
        public Descriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ValueChainStageType", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum ValueChainStageType1 {
        
        /// <remarks/>
        Outcome,
        
        /// <remarks/>
        Output_Processing,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        Input_Processing,
        
        /// <remarks/>
        Input,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum PerformanceIndicatorTypeType {
        
        /// <remarks/>
        Quantitative,
        
        /// <remarks/>
        Qualitative,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public partial class GoalType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string identifierField;
        
        private string sequenceIndicatorField;
        
        private Stakeholder[] stakeholderField;
        
        private string otherInformationField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Stakeholder")]
        public Stakeholder[] Stakeholder {
            get {
                return this.stakeholderField;
            }
            set {
                this.stakeholderField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    [System.Xml.Serialization.XmlRootAttribute("Submitter", Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport", IsNullable=false)]
    public partial class ContactInformationType {
        
        private string identifierField;
        
        private string givenNameField;
        
        private string surnameField;
        
        private string phoneNumberField;
        
        private string emailAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:ISO:std:iso:17469:tech:xsd:PerformancePlanOrReport")]
    public enum PerformancePlanOrReportType {
        
        /// <remarks/>
        Strategic_Plan,
        
        /// <remarks/>
        Performance_Plan,
        
        /// <remarks/>
        Performance_Report,
    }
}
