//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace StratML.Core.ThreeFive {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.stratml.us/3.5", IsNullable=false)]
    public partial class OrganizationalStrategyDocument : Strategy {
        
        private Organization organizationField;
        
        private Individual submitterField;
        
        private AdministrativeInformation administrativeInformationField;
        
        /// <remarks/>
        public Organization Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public Individual Submitter {
            get {
                return this.submitterField;
            }
            set {
                this.submitterField = value;
            }
        }
        
        /// <remarks/>
        public AdministrativeInformation AdministrativeInformation {
            get {
                return this.administrativeInformationField;
            }
            set {
                this.administrativeInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationStakeholder))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Organization : Group {
        
        private Strategy strategyField;
        
        private Organization[] organization1Field;
        
        /// <remarks/>
        public Strategy Strategy {
            get {
                return this.strategyField;
            }
            set {
                this.strategyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization")]
        public Organization[] Organization1 {
            get {
                return this.organization1Field;
            }
            set {
                this.organization1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Strategy : NameIdentifier {
        
        private Mission missionField;
        
        private Vision visionField;
        
        private Value[] valueField;
        
        private Goal[] goalField;
        
        private DrivingForce drivingForceField;
        
        private StrategyFramework[] frameworkField;
        
        /// <remarks/>
        public Mission Mission {
            get {
                return this.missionField;
            }
            set {
                this.missionField = value;
            }
        }
        
        /// <remarks/>
        public Vision Vision {
            get {
                return this.visionField;
            }
            set {
                this.visionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public Value[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Goal")]
        public Goal[] Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
        
        /// <remarks/>
        public DrivingForce DrivingForce {
            get {
                return this.drivingForceField;
            }
            set {
                this.drivingForceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Framework")]
        public StrategyFramework[] Framework {
            get {
                return this.frameworkField;
            }
            set {
                this.frameworkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Mission : ArtifactBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Artifact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Goal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PerformanceIndicator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Objective))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Vision))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mission))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class ArtifactBase : NameIdentifier {
        
        private ArtifactBaseStakeholders stakeholdersField;
        
        private string otherInformationField;
        
        /// <remarks/>
        public ArtifactBaseStakeholders Stakeholders {
            get {
                return this.stakeholdersField;
            }
            set {
                this.stakeholdersField = value;
            }
        }
        
        /// <remarks/>
        public string OtherInformation {
            get {
                return this.otherInformationField;
            }
            set {
                this.otherInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    public partial class ArtifactBaseStakeholders {
        
        private IndividualStakeholder[] individualField;
        
        private OrganizationStakeholder[] organizationField;
        
        private GroupStakeholder[] groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Individual")]
        public IndividualStakeholder[] Individual {
            get {
                return this.individualField;
            }
            set {
                this.individualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Organization")]
        public OrganizationStakeholder[] Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Group")]
        public GroupStakeholder[] Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class IndividualStakeholder : Individual {
        
        private Relationship[] relationshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Relationship : NameIdentifier {
        
        private string[] referentIdentifierField;
        
        private RelationshipType relationshipTypeField;
        
        public Relationship() {
            this.relationshipTypeField = RelationshipType.Peer_To;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferentIdentifier", DataType="IDREF")]
        public string[] ReferentIdentifier {
            get {
                return this.referentIdentifierField;
            }
            set {
                this.referentIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RelationshipType.Peer_To)]
        public RelationshipType RelationshipType {
            get {
                return this.relationshipTypeField;
            }
            set {
                this.relationshipTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum RelationshipType {
        
        /// <remarks/>
        Broader_Than,
        
        /// <remarks/>
        Peer_To,
        
        /// <remarks/>
        Narrower_Than,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StrategyFramework))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DrivingForce))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SuccessFactor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Score))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RatingSet))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManagementChallenge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Category))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CategoryGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Relationship))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Role))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContactMechanism))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Email))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhysicalAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Actor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationStakeholder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupStakeholder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Individual))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndividualStakeholder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Authority))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArtifactBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Artifact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Goal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PerformanceIndicator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Objective))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Vision))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Mission))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Strategy))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Map))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class NameIdentifier {
        
        private string identiferField;
        
        private string referenceIdentifierField;
        
        private string nameField;
        
        private string descriptionField;
        
        private Map[] mapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifer {
            get {
                return this.identiferField;
            }
            set {
                this.identiferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="IDREF")]
        public string ReferenceIdentifier {
            get {
                return this.referenceIdentifierField;
            }
            set {
                this.referenceIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Map")]
        public Map[] Map {
            get {
                return this.mapField;
            }
            set {
                this.mapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Map : NameIdentifier {
        
        private MapType typeField;
        
        private double weightField;
        
        private System.DateTime publicationDateField;
        
        private bool publicationDateFieldSpecified;
        
        private string[] mappedIdentifierField;
        
        public Map() {
            this.typeField = MapType.Relationship;
            this.weightField = 1D;
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(MapType.Relationship)]
        public MapType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public double Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublicationDateSpecified {
            get {
                return this.publicationDateFieldSpecified;
            }
            set {
                this.publicationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MappedIdentifier", DataType="IDREF")]
        public string[] MappedIdentifier {
            get {
                return this.mappedIdentifierField;
            }
            set {
                this.mappedIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum MapType {
        
        /// <remarks/>
        Relationship,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        Supports,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class AdministrativeInformation {
        
        private string identifierField;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        private System.DateTime publicationDateField;
        
        private string sourceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PublicationDate {
            get {
                return this.publicationDateField;
            }
            set {
                this.publicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasurementResultDescriptor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasurementResultScore))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MeasurementResultUnits))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResult {
        
        private string identifierField;
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResultDescriptor : MeasurementResult {
        
        private MeasurementResultDescriptorDescriptor descriptorField;
        
        /// <remarks/>
        public MeasurementResultDescriptorDescriptor Descriptor {
            get {
                return this.descriptorField;
            }
            set {
                this.descriptorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResultDescriptorDescriptor {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResultScore : MeasurementResult {
        
        private RatingSet ratingSetField;
        
        private Score scoreField;
        
        /// <remarks/>
        public RatingSet RatingSet {
            get {
                return this.ratingSetField;
            }
            set {
                this.ratingSetField = value;
            }
        }
        
        /// <remarks/>
        public Score Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class RatingSet : NameIdentifier {
        
        private Score[] scoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Score")]
        public Score[] Score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Score : NameIdentifier {
        
        private string weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class MeasurementResultUnits : MeasurementResult {
        
        private double numberOfUnitsField;
        
        /// <remarks/>
        public double NumberOfUnits {
            get {
                return this.numberOfUnitsField;
            }
            set {
                this.numberOfUnitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class ContactInformation {
        
        private string identifierField;
        
        private PhoneNumber[] phoneNumberField;
        
        private Email[] emailAddressField;
        
        private PhysicalAddress[] addressField;
        
        private WebAddress[] websiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhoneNumber")]
        public PhoneNumber[] PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmailAddress")]
        public Email[] EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Address")]
        public PhysicalAddress[] Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Website")]
        public WebAddress[] Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class PhoneNumber : ContactMechanism {
        
        private string numberField;
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WebAddress))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Email))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneNumber))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhysicalAddress))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class ContactMechanism : NameIdentifier {
        
        private string typeField;
        
        public ContactMechanism() {
            this.typeField = "Primary";
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute("Primary")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class WebAddress : ContactMechanism {
        
        private string webAddress1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("WebAddress")]
        public string WebAddress1 {
            get {
                return this.webAddress1Field;
            }
            set {
                this.webAddress1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Email : ContactMechanism {
        
        private string email1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string Email1 {
            get {
                return this.email1Field;
            }
            set {
                this.email1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class PhysicalAddress : ContactMechanism {
        
        private string addressLabelField;
        
        private string streetField;
        
        private string localityField;
        
        private string regionField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string pOBoxField;
        
        private string extendedAddressField;
        
        /// <remarks/>
        public string AddressLabel {
            get {
                return this.addressLabelField;
            }
            set {
                this.addressLabelField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string Region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string POBox {
            get {
                return this.pOBoxField;
            }
            set {
                this.pOBoxField = value;
            }
        }
        
        /// <remarks/>
        public string ExtendedAddress {
            get {
                return this.extendedAddressField;
            }
            set {
                this.extendedAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class StrategyFramework : NameIdentifier {
        
        private System.Xml.XmlElement dataField;
        
        /// <remarks/>
        public System.Xml.XmlElement Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class DrivingForce : NameIdentifier {
        
        private InhibitingOrEnabling inhibitingOrEnablingField;
        
        private InternalOrExternal internalOrExternalField;
        
        /// <remarks/>
        public InhibitingOrEnabling InhibitingOrEnabling {
            get {
                return this.inhibitingOrEnablingField;
            }
            set {
                this.inhibitingOrEnablingField = value;
            }
        }
        
        /// <remarks/>
        public InternalOrExternal InternalOrExternal {
            get {
                return this.internalOrExternalField;
            }
            set {
                this.internalOrExternalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum InhibitingOrEnabling {
        
        /// <remarks/>
        Enabling,
        
        /// <remarks/>
        Inhibiting,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum InternalOrExternal {
        
        /// <remarks/>
        Internal,
        
        /// <remarks/>
        External,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class SuccessFactor : NameIdentifier {
        
        private Criticality criticalityField;
        
        private InternalOrExternal internalOrExternalField;
        
        /// <remarks/>
        public Criticality Criticality {
            get {
                return this.criticalityField;
            }
            set {
                this.criticalityField = value;
            }
        }
        
        /// <remarks/>
        public InternalOrExternal InternalOrExternal {
            get {
                return this.internalOrExternalField;
            }
            set {
                this.internalOrExternalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum Criticality {
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        Contributory,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class ManagementChallenge : NameIdentifier {
        
        private Priority probabilityField;
        
        private Priority impactField;
        
        /// <remarks/>
        public Priority Probability {
            get {
                return this.probabilityField;
            }
            set {
                this.probabilityField = value;
            }
        }
        
        /// <remarks/>
        public Priority Impact {
            get {
                return this.impactField;
            }
            set {
                this.impactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum Priority {
        
        /// <remarks/>
        To_Be_Determined,
        
        /// <remarks/>
        High,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Low,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Category : NameIdentifier {
        
        private WebAddress websiteField;
        
        /// <remarks/>
        public WebAddress Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class CategoryGroup : NameIdentifier {
        
        private Category[] categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category")]
        public Category[] Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Role : NameIdentifier {
        
        private RoleType roleTypeField;
        
        private bool roleTypeFieldSpecified;
        
        /// <remarks/>
        public RoleType RoleType {
            get {
                return this.roleTypeField;
            }
            set {
                this.roleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoleTypeSpecified {
            get {
                return this.roleTypeFieldSpecified;
            }
            set {
                this.roleTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum RoleType {
        
        /// <remarks/>
        Performer,
        
        /// <remarks/>
        Beneficiary,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Group))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationStakeholder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupStakeholder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Individual))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndividualStakeholder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Authority))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Actor : NameIdentifier {
        
        private ContactInformation contactField;
        
        private Role[] roleField;
        
        private Competency[] competencyField;
        
        private NameIdentifier[] valuePropositionField;
        
        /// <remarks/>
        public ContactInformation Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Role")]
        public Role[] Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Competency")]
        public Competency[] Competency {
            get {
                return this.competencyField;
            }
            set {
                this.competencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ValueProposition")]
        public NameIdentifier[] ValueProposition {
            get {
                return this.valuePropositionField;
            }
            set {
                this.valuePropositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum Competency {
        
        /// <remarks/>
        Core,
        
        /// <remarks/>
        Supporting,
        
        /// <remarks/>
        Ancillary,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Organization))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrganizationStakeholder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupStakeholder))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Group : Actor {
        
        private Individual[] individualField;
        
        private string acronymField;
        
        private SpecialOrganizationType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Individual")]
        public Individual[] Individual {
            get {
                return this.individualField;
            }
            set {
                this.individualField = value;
            }
        }
        
        /// <remarks/>
        public string Acronym {
            get {
                return this.acronymField;
            }
            set {
                this.acronymField = value;
            }
        }
        
        /// <remarks/>
        public SpecialOrganizationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IndividualStakeholder))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Individual : Actor {
        
        private string givenNameField;
        
        private string surnameField;
        
        /// <remarks/>
        public string GivenName {
            get {
                return this.givenNameField;
            }
            set {
                this.givenNameField = value;
            }
        }
        
        /// <remarks/>
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum SpecialOrganizationType {
        
        /// <remarks/>
        Board_of_Directors,
        
        /// <remarks/>
        Committee,
        
        /// <remarks/>
        Conference,
        
        /// <remarks/>
        Consortium,
        
        /// <remarks/>
        Cooperative,
        
        /// <remarks/>
        Exposition,
        
        /// <remarks/>
        Family,
        
        /// <remarks/>
        Individual,
        
        /// <remarks/>
        Initiative,
        
        /// <remarks/>
        Investment,
        
        /// <remarks/>
        Program,
        
        /// <remarks/>
        Project,
        
        /// <remarks/>
        Student,
        
        /// <remarks/>
        System,
        
        /// <remarks/>
        Virtual,
        
        /// <remarks/>
        Work_Group,
        
        /// <remarks/>
        Other,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class GroupStakeholder : Group {
        
        private Relationship[] relationshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Authority : Actor {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class OrganizationStakeholder : Organization {
        
        private Relationship[] relationshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Relationship")]
        public Relationship[] Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Goal))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PerformanceIndicator))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Objective))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Value))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Artifact : ArtifactBase {
        
        private string sequenceIndicatorField;
        
        /// <remarks/>
        public string SequenceIndicator {
            get {
                return this.sequenceIndicatorField;
            }
            set {
                this.sequenceIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Goal : Artifact {
        
        private Objective[] objectiveField;
        
        private Authority[] authorityField;
        
        private PhysicalAddress placeField;
        
        private SuccessFactor successFactorField;
        
        private Priority priorityField;
        
        private bool priorityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Objective")]
        public Objective[] Objective {
            get {
                return this.objectiveField;
            }
            set {
                this.objectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Authority")]
        public Authority[] Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public PhysicalAddress Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        public SuccessFactor SuccessFactor {
            get {
                return this.successFactorField;
            }
            set {
                this.successFactorField = value;
            }
        }
        
        /// <remarks/>
        public Priority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrioritySpecified {
            get {
                return this.priorityFieldSpecified;
            }
            set {
                this.priorityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Objective : Artifact {
        
        private CategoryGroup[] categorizationField;
        
        private ManagementChallenge[] managementChallengeField;
        
        private PerformanceIndicator[] performanceIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categorization")]
        public CategoryGroup[] Categorization {
            get {
                return this.categorizationField;
            }
            set {
                this.categorizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManagementChallenge")]
        public ManagementChallenge[] ManagementChallenge {
            get {
                return this.managementChallengeField;
            }
            set {
                this.managementChallengeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PerformanceIndicator")]
        public PerformanceIndicator[] PerformanceIndicator {
            get {
                return this.performanceIndicatorField;
            }
            set {
                this.performanceIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class PerformanceIndicator : Artifact {
        
        private NameIdentifier measurementDimensionField;
        
        private NameIdentifier unitOfMeasurementField;
        
        private PerformanceIndicatorTargetResults targetResultsField;
        
        private PerformanceIndicatorActualResults actualResultsField;
        
        private CategoryGroup[] categorizationField;
        
        private Keyness keynessField;
        
        private bool keynessFieldSpecified;
        
        private ValueChainStageType valueChainStageField;
        
        private bool valueChainStageFieldSpecified;
        
        /// <remarks/>
        public NameIdentifier MeasurementDimension {
            get {
                return this.measurementDimensionField;
            }
            set {
                this.measurementDimensionField = value;
            }
        }
        
        /// <remarks/>
        public NameIdentifier UnitOfMeasurement {
            get {
                return this.unitOfMeasurementField;
            }
            set {
                this.unitOfMeasurementField = value;
            }
        }
        
        /// <remarks/>
        public PerformanceIndicatorTargetResults TargetResults {
            get {
                return this.targetResultsField;
            }
            set {
                this.targetResultsField = value;
            }
        }
        
        /// <remarks/>
        public PerformanceIndicatorActualResults ActualResults {
            get {
                return this.actualResultsField;
            }
            set {
                this.actualResultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Categorization")]
        public CategoryGroup[] Categorization {
            get {
                return this.categorizationField;
            }
            set {
                this.categorizationField = value;
            }
        }
        
        /// <remarks/>
        public Keyness Keyness {
            get {
                return this.keynessField;
            }
            set {
                this.keynessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KeynessSpecified {
            get {
                return this.keynessFieldSpecified;
            }
            set {
                this.keynessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ValueChainStageType ValueChainStage {
            get {
                return this.valueChainStageField;
            }
            set {
                this.valueChainStageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueChainStageSpecified {
            get {
                return this.valueChainStageFieldSpecified;
            }
            set {
                this.valueChainStageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    public partial class PerformanceIndicatorTargetResults {
        
        private MeasurementResultUnits[] unitResultField;
        
        private MeasurementResultDescriptor[] descriptorResultField;
        
        private MeasurementResultScore[] scoredResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnitResult")]
        public MeasurementResultUnits[] UnitResult {
            get {
                return this.unitResultField;
            }
            set {
                this.unitResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DescriptorResult")]
        public MeasurementResultDescriptor[] DescriptorResult {
            get {
                return this.descriptorResultField;
            }
            set {
                this.descriptorResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScoredResult")]
        public MeasurementResultScore[] ScoredResult {
            get {
                return this.scoredResultField;
            }
            set {
                this.scoredResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.stratml.us/3.5")]
    public partial class PerformanceIndicatorActualResults {
        
        private MeasurementResultUnits[] unitResultField;
        
        private MeasurementResultDescriptor[] descriptorResultField;
        
        private MeasurementResultScore[] scoredResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UnitResult")]
        public MeasurementResultUnits[] UnitResult {
            get {
                return this.unitResultField;
            }
            set {
                this.unitResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DescriptorResult")]
        public MeasurementResultDescriptor[] DescriptorResult {
            get {
                return this.descriptorResultField;
            }
            set {
                this.descriptorResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScoredResult")]
        public MeasurementResultScore[] ScoredResult {
            get {
                return this.scoredResultField;
            }
            set {
                this.scoredResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum Keyness {
        
        /// <remarks/>
        To_Be_Determined,
        
        /// <remarks/>
        Key,
        
        /// <remarks/>
        Secondary,
        
        /// <remarks/>
        Ancillary,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public enum ValueChainStageType {
        
        /// <remarks/>
        Outcome,
        
        /// <remarks/>
        Output_Processing,
        
        /// <remarks/>
        Output,
        
        /// <remarks/>
        Input_Processing,
        
        /// <remarks/>
        Input,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Value : Artifact {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.stratml.us/3.5")]
    public partial class Vision : ArtifactBase {
    }
}
